### ISSUE TITLE
[Feature] Sylius 1.11 support

### ISSUE THREAD

**Issue by Geolim4** [synolia/SyliusSchedulerCommandPlugin#86]
**Is your feature request related to a problem? Please describe.**
Hello, all in the title, do you plan to support Sylius 1.11 anytime soon ?

**Comment by Jibbarth** [comment]
Hello @Geolim4 

This plugin should already have sylius 1.11 support, and i use it on a sylius 1.12 too. 


However, from your exception screen, I bet the issue is related to #35 

Can you check the output of the command: 
```
php bin/console list --json 
```

I already had a case that the output full output was not a correct json, that could lead to this error.
